import Head from 'next/head'
import Image from 'next/image'
import { useAuth } from '../lib/auth'
import styles from '../styles/Home.module.css'

export default function Home() {
  const auth = useAuth()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Fast Feedback 
        </h1>
        <button onClick={(e) => auth.signinWithGithub()}>Signin</button>
        {auth?.user && <button onClick={(e) => auth.signout()}>Signout</button>}
        <div>{auth?.user?.displayName}</div>
        <div>{auth?.user?.email}</div>
        {auth?.user ? <img src={auth?.user?.photoURL} alt="Vercel Logo" width={150} height={150} /> : ''}
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
